apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-worker
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-worker
  template:
    metadata:
      labels:
        app: cloud-worker
    spec:
      nodeSelector:
        testbed-role: Cloud
      containers:
      - name: worker
        image: pandora-dnn:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 6999
